import type { Metadata } from "next"
// import localFont from 'next/font/local'
import "./globals.css"
 

// const geistSans = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Geist/gyByhwUxId8gMEwcGFU.woff2',
//       weight: '100 900',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-geist-sans',
//   display: 'swap',
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
